// src/client/scripts/esm/game/misc/enginelegalmovesdebug.ts

/**
 * Shared debug overlay for legal moves generated by an engine worker.
 */

import type { Coords } from '../../../../../shared/chess/util/coordutil.js';
import type { GameFile } from '../../../../../shared/chess/logic/gamefile.js';

import icnconverter from '../../../../../shared/chess/logic/icn/icnconverter.js';
import coordutil, { CoordsKey } from '../../../../../shared/chess/util/coordutil.js';

import toast from '../../components/toast.js';
import gameslot from '../chess/gameslot.js';
import boardpos from '../rendering/boardpos.js';
import snapping from '../rendering/highlights/snapping.js';
import drawsquares from '../rendering/highlights/annotations/drawsquares.js';
import { GameBus } from '../GameBus.js';
import frametracker from '../rendering/frametracker.js';
import gamecompressor from '../chess/gamecompressor.js';
import squarerendering from '../rendering/highlights/squarerendering.js';

interface DebugMoveRequest {
	id: number;
	key: string;
	gamefile: GameFile;
	positionIcn: string;
}

interface EngineLegalMovesDebugOptions {
	canRequest: () => boolean;
	requestMoves: (request: DebugMoveRequest) => void;
}

let initialized = false;
let enabled = false;
let nextRequestId = 1;
let options: EngineLegalMovesDebugOptions | undefined;

const legalMovesByPosition = new Map<string, string[]>();
const requestKeyById = new Map<number, string>();
const pendingRequestIds: number[] = [];

/** Wires up the overlay's engine hooks and (once) its GameBus listeners. */
function init(nextOptions: EngineLegalMovesDebugOptions): void {
	options = nextOptions;
	if (initialized) return;
	initialized = true;

	GameBus.addEventListener('engine-debug', () => toggle());
	GameBus.addEventListener('render-below-pieces', () => render());
	GameBus.addEventListener('view-move', () => requestMovesForCurrentPosition());
	GameBus.addEventListener('game-unloaded', () => clear());
}

/** Toggles the overlay on/off, requesting moves when enabling and dropping pending requests when disabling. */
function toggle(): void {
	if (enabled) {
		disable();
		toast.show('Engine legal moves debug off');
		return;
	}
	if (!options?.canRequest()) {
		toast.show('Engine legal moves debug disabled: pieces outside world border', {
			error: true,
		});
		return;
	}
	enabled = true;
	console.log('Toggled engine move gen highlights: true');
	toast.show('Engine legal moves debug on');
	requestMovesForCurrentPosition();
}

/** Forces the overlay off, e.g. when the position goes outside the engine's safe world border. No-op if already off. */
function disable(): void {
	if (!enabled) return;
	enabled = false;
	console.log('Toggled engine move gen highlights: false');
	requestKeyById.clear();
	pendingRequestIds.length = 0;
	frametracker.onVisualChange();
}

/** Requests the engine's legal moves for the viewed position, skipping if already cached or in flight. */
function requestMovesForCurrentPosition(): void {
	if (!enabled || !options?.canRequest()) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const key = getPositionKey(gamefile);
	if (legalMovesByPosition.has(key)) {
		frametracker.onVisualChange();
		return;
	}
	if ([...requestKeyById.values()].includes(key)) return;

	const id = nextRequestId++;
	const request = { id, key, gamefile, positionIcn: key };
	requestKeyById.set(id, key);
	pendingRequestIds.push(id);
	options.requestMoves(request);
}

/** Caches a request's returned moves against its position key and clears its pending state. */
function receiveMoves(requestId: number, moves: string[]): void {
	const key = requestKeyById.get(requestId);
	if (!key) return;
	requestKeyById.delete(requestId);
	removePendingRequest(requestId);
	legalMovesByPosition.set(key, moves);
	frametracker.onVisualChange();
}

/** Assigns a response to the oldest outstanding request, for engines that reply in FIFO order without ids. */
function receiveMovesForOldestRequest(moves: string[]): void {
	const requestId = pendingRequestIds.shift();
	if (requestId === undefined) return;
	receiveMoves(requestId, moves);
}

/** Removes a request id from the pending queue. */
function removePendingRequest(requestId: number): void {
	const index = pendingRequestIds.indexOf(requestId);
	if (index !== -1) pendingRequestIds.splice(index, 1);
}

/** Returns the compact ICN of the viewed position, used as the cache/request key. */
function getPositionKey(gamefile: GameFile): string {
	const longformIn = gamecompressor.compressGamefile(gamefile, true);
	return icnconverter.LongToShort_Format(longformIn, {
		compact: true,
		skipPosition: false,
		spaces: false,
		comments: false,
		make_new_lines: false,
		move_numbers: false,
	});
}

/** Renders the cached legal-move destinations for the viewed position as highlighted squares. */
function render(): void {
	if (!enabled) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const moves = legalMovesByPosition.get(getPositionKey(gamefile));
	if (!moves?.length) return;

	const coords = moves
		.map(getMoveDestination)
		.filter((coord): coord is Coords => coord !== undefined);
	if (coords.length === 0) return;

	const u_size = boardpos.areZoomedOut()
		? snapping.getEntityWidthWorld()
		: boardpos.getBoardScaleAsNumber();

	squarerendering.genModel(coords, drawsquares.PRESET_SQUARE_COLOR).render(undefined, undefined, {
		u_size,
	});
}

/** Parses the destination coords out of a compact move token ("from>to=promotion"), or undefined if malformed. */
function getMoveDestination(move: string): Coords | undefined {
	const to = move.split('>')[1]?.split('=')[0];
	if (!to) return undefined;
	try {
		return coordutil.getCoordsFromKey(to as CoordsKey);
	} catch {
		return undefined;
	}
}

/** Drops all cached moves and pending requests (on game unload). */
function clear(): void {
	legalMovesByPosition.clear();
	requestKeyById.clear();
	pendingRequestIds.length = 0;
	frametracker.onVisualChange();
}

export default {
	init,
	disable,
	receiveMoves,
	receiveMovesForOldestRequest,
	requestMovesForCurrentPosition,
};
