// src/client/scripts/esm/game/misc/enginelegalmovesdebug.ts

/**
 * Shared debug overlay for legal moves generated by an engine worker.
 */

import type { Coords } from '../../../../../shared/chess/util/coordutil.js';
import type { GameFile } from '../../../../../shared/chess/logic/gamefile.js';

import icnconverter from '../../../../../shared/chess/logic/icn/icnconverter.js';
import coordutil, { CoordsKey } from '../../../../../shared/chess/util/coordutil.js';

import gameslot from '../chess/gameslot.js';
import boardpos from '../rendering/boardpos.js';
import snapping from '../rendering/highlights/snapping.js';
import drawsquares from '../rendering/highlights/annotations/drawsquares.js';
import { GameBus } from '../GameBus.js';
import frametracker from '../rendering/frametracker.js';
import gamecompressor from '../chess/gamecompressor.js';
import squarerendering from '../rendering/highlights/squarerendering.js';

interface DebugMoveRequest {
	id: number;
	key: string;
	gamefile: GameFile;
	positionIcn: string;
}

interface EngineLegalMovesDebugOptions {
	canRequest: () => boolean;
	requestMoves: (request: DebugMoveRequest) => void;
}

let initialized = false;
let enabled = false;
let nextRequestId = 1;
let options: EngineLegalMovesDebugOptions | undefined;

const legalMovesByPosition = new Map<string, string[]>();
const requestKeyById = new Map<number, string>();
const pendingRequestIds: number[] = [];

function init(nextOptions: EngineLegalMovesDebugOptions): void {
	options = nextOptions;
	if (initialized) return;
	initialized = true;

	GameBus.addEventListener('engine-debug', () => toggle());
	GameBus.addEventListener('render-below-pieces', () => render());
	GameBus.addEventListener('view-move', () => requestMovesForCurrentPosition());
	GameBus.addEventListener('game-unloaded', () => clear());
}

function toggle(): void {
	enabled = !enabled;
	console.log(`Toggled engine move gen highlights: ${enabled}`);

	if (!enabled) {
		requestKeyById.clear();
		pendingRequestIds.length = 0;
		frametracker.onVisualChange();
		return;
	}
	requestMovesForCurrentPosition();
}

function requestMovesForCurrentPosition(): void {
	if (!enabled || !options?.canRequest()) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const key = getPositionKey(gamefile);
	if (legalMovesByPosition.has(key)) {
		frametracker.onVisualChange();
		return;
	}
	if ([...requestKeyById.values()].includes(key)) return;

	const id = nextRequestId++;
	const request = { id, key, gamefile, positionIcn: key };
	requestKeyById.set(id, key);
	pendingRequestIds.push(id);
	options.requestMoves(request);
}

function receiveMoves(requestId: number, moves: string[]): void {
	const key = requestKeyById.get(requestId);
	if (!key) return;
	requestKeyById.delete(requestId);
	removePendingRequest(requestId);
	legalMovesByPosition.set(key, moves);
	frametracker.onVisualChange();
}

function receiveMovesForOldestRequest(moves: string[]): void {
	const requestId = pendingRequestIds.shift();
	if (requestId === undefined) return;
	receiveMoves(requestId, moves);
}

function removePendingRequest(requestId: number): void {
	const index = pendingRequestIds.indexOf(requestId);
	if (index !== -1) pendingRequestIds.splice(index, 1);
}

function getPositionKey(gamefile: GameFile): string {
	const longformIn = gamecompressor.compressGamefile(gamefile, true);
	return icnconverter.LongToShort_Format(longformIn, {
		compact: true,
		skipPosition: false,
		spaces: false,
		comments: false,
		make_new_lines: false,
		move_numbers: false,
	});
}

function render(): void {
	if (!enabled) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const moves = legalMovesByPosition.get(getPositionKey(gamefile));
	if (!moves?.length) return;

	const coords = moves
		.map(getMoveDestination)
		.filter((coord): coord is Coords => coord !== undefined);
	if (coords.length === 0) return;

	const u_size = boardpos.areZoomedOut()
		? snapping.getEntityWidthWorld()
		: boardpos.getBoardScaleAsNumber();

	squarerendering.genModel(coords, drawsquares.PRESET_SQUARE_COLOR).render(undefined, undefined, {
		u_size,
	});
}

function getMoveDestination(move: string): Coords | undefined {
	const to = move.split('>')[1]?.split('=')[0];
	if (!to) return undefined;
	try {
		return coordutil.getCoordsFromKey(to as CoordsKey);
	} catch {
		return undefined;
	}
}

function clear(): void {
	legalMovesByPosition.clear();
	requestKeyById.clear();
	pendingRequestIds.length = 0;
	frametracker.onVisualChange();
}

export default {
	init,
	receiveMoves,
	receiveMovesForOldestRequest,
	requestMovesForCurrentPosition,
};
