// src/client/scripts/esm/game/misc/enginelegalmovesdebug.ts

/**
 * Shared debug overlay for legal moves generated by an engine worker.
 */

import type { Coords } from '../../../../../shared/chess/util/coordutil.js';
import type { GameFile } from '../../../../../shared/chess/logic/gamefile.js';

import icnconverter from '../../../../../shared/chess/logic/icn/icnconverter.js';
import coordutil, { CoordsKey } from '../../../../../shared/chess/util/coordutil.js';

import toast from '../../components/toast.js';
import gameslot from '../chess/gameslot.js';
import boardpos from '../rendering/boardpos.js';
import snapping from '../rendering/highlights/snapping.js';
import drawsquares from '../rendering/highlights/annotations/drawsquares.js';
import { GameBus } from '../GameBus.js';
import frametracker from '../rendering/frametracker.js';
import gamecompressor from '../chess/gamecompressor.js';
import squarerendering from '../rendering/highlights/squarerendering.js';

/** A move request dispatched to the engine worker for a specific position. */
interface DebugMoveRequest {
	/** Unique id for correlating this request with its response. */
	id: number;
	/** Compact ICN position key, used as the cache key. */
	key: string;
	/** The game state to compute legal moves for. */
	gamefile: GameFile;
	/** Compact ICN of the position (same as `key`). */
	positionIcn: string;
}

/** Callbacks provided by the engine consumer to wire the overlay into a specific engine worker. */
interface EngineLegalMovesDebugOptions {
	/** Returns true when the engine can be asked for moves right now. */
	canRequest: () => boolean;
	/**
	 * The user-facing reason the overlay can't be enabled in this position
	 * or undefined when it can. Omit if the engine has no such positions.
	 */
	getBlockedReason?: () => string | undefined;
	/** Sends `request` to the engine worker. */
	requestMoves: (request: DebugMoveRequest) => void;
	/**
	 * Frees whatever dedicated resource `requestMoves` lazily spun up (e.g. ceval's idle
	 * helper worker), since the overlay is off and won't be requesting again until re-enabled.
	 * Omit if the consumer has no separate resource to free (e.g. a single always-on worker).
	 */
	release?: () => void;
}

/** Whether the GameBus listeners have been registered. */
let initialized = false;
/** Whether the overlay is currently active. */
let enabled = false;
/** Monotonically increasing counter used to assign unique request ids. */
let nextRequestId = 1;
/** Engine hooks provided by the consumer via {@link init}. */
let options: EngineLegalMovesDebugOptions | undefined;

/** Legal move lists keyed by compact ICN position string. */
const legalMovesByPosition = new Map<string, string[]>();
/** Maps each in-flight request id to its position key. */
const requestKeyById = new Map<number, string>();
/** Ordered queue of in-flight request ids, used for FIFO response matching. */
const pendingRequestIds: number[] = [];

/** Wires up the overlay's engine hooks and (once) its GameBus listeners. Call only when an engine exists. */
function init(nextOptions: EngineLegalMovesDebugOptions): void {
	options = nextOptions;
	if (initialized) return;
	initialized = true;

	GameBus.addEventListener('engine-debug', () => toggle());
	GameBus.addEventListener('render-below-pieces', () => render());
	GameBus.addEventListener('view-move', () => requestMovesForCurrentPosition());
	GameBus.addEventListener('game-unloaded', () => clear());
}

/** Uninstalls the hooks when the engine goes away, leaving the overlay off and its toggle inert. */
function detach(): void {
	disable();
	options = undefined;
}

/** Toggles the overlay on/off, requesting moves when enabling and dropping pending requests when disabling. */
function toggle(): void {
	if (!options) return; // No engine here (e.g. spectating) — the overlay isn't installed.
	if (enabled) {
		disable();
		return;
	}
	const blockedReason = options.getBlockedReason?.();
	if (blockedReason !== undefined) {
		toast.show(`Engine legal moves debug unavailable: ${blockedReason}`, { error: true });
		return;
	}
	enabled = true;
	console.log('Toggled engine debug: true');
	requestMovesForCurrentPosition();
}

/**
 * Forces the overlay off, e.g. when the position goes outside
 * the engine's safe world border. No-op if already off.
 */
function disable(): void {
	if (!enabled) return;
	enabled = false;
	console.log('Toggled engine debug: false');
	requestKeyById.clear();
	pendingRequestIds.length = 0;
	options?.release?.();
	frametracker.onVisualChange();
}

/** Requests the engine's legal moves for the viewed position, skipping if already cached or in flight. */
function requestMovesForCurrentPosition(): void {
	if (!enabled || !options?.canRequest()) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const key = getPositionKey(gamefile);
	if (legalMovesByPosition.has(key)) {
		frametracker.onVisualChange();
		return;
	}
	if ([...requestKeyById.values()].includes(key)) return;

	const id = nextRequestId++;
	const request = { id, key, gamefile, positionIcn: key };
	requestKeyById.set(id, key);
	pendingRequestIds.push(id);
	options.requestMoves(request);
}

/** Caches a request's returned moves against its position key and clears its pending state. */
function receiveMoves(requestId: number, moves: string[]): void {
	const key = requestKeyById.get(requestId);
	if (!key) return;
	requestKeyById.delete(requestId);
	removePendingRequest(requestId);
	legalMovesByPosition.set(key, moves);
	frametracker.onVisualChange();
}

/** Assigns a response to the oldest outstanding request, for engines that reply in FIFO order without ids. */
function receiveMovesForOldestRequest(moves: string[]): void {
	const requestId = pendingRequestIds.shift();
	if (requestId === undefined) return;
	receiveMoves(requestId, moves);
}

/** Removes a request id from the pending queue. */
function removePendingRequest(requestId: number): void {
	const index = pendingRequestIds.indexOf(requestId);
	if (index !== -1) pendingRequestIds.splice(index, 1);
}

/** Returns the compact ICN of the viewed position, used as the cache/request key. */
function getPositionKey(gamefile: GameFile): string {
	const longformIn = gamecompressor.compressGamefile(gamefile, true);
	return icnconverter.getShortFormPosition(
		longformIn.position!,
		longformIn.state_global.specialRights!,
	);
}

/** Renders the cached legal-move destinations for the viewed position as highlighted squares. */
function render(): void {
	if (!enabled) return;

	const gamefile = gameslot.getGamefile();
	if (!gamefile) return;

	const moves = legalMovesByPosition.get(getPositionKey(gamefile));
	if (!moves?.length) return;

	const coords = moves
		.map(getMoveDestination)
		.filter((coord): coord is Coords => coord !== undefined);
	if (coords.length === 0) return;

	const u_size = boardpos.areZoomedOut()
		? snapping.getEntityWidthWorld()
		: boardpos.getBoardScaleAsNumber();

	squarerendering.genModel(coords, drawsquares.PRESET_SQUARE_COLOR).render(undefined, undefined, {
		u_size,
	});
}

/** Parses the destination coords out of a compact move token ("from>to=promotion"), or undefined if malformed. */
function getMoveDestination(move: string): Coords | undefined {
	const to = move.split('>')[1]?.split('=')[0];
	if (!to) return undefined;
	try {
		return coordutil.getCoordsFromKey(to as CoordsKey);
	} catch {
		return undefined;
	}
}

/** Drops all cached moves and pending requests (on game unload). */
function clear(): void {
	legalMovesByPosition.clear();
	requestKeyById.clear();
	pendingRequestIds.length = 0;
	frametracker.onVisualChange();
}

export default {
	init,
	detach,
	disable,
	receiveMoves,
	receiveMovesForOldestRequest,
	requestMovesForCurrentPosition,
};
