// src/client/types/translations/header.ts

/**
 * This file is auto-generated by scripts/generate-translation-types.ts.
 * Do NOT edit manually!
 *
 * Client-side translation keys for the "header" component.
 * These are the only translation strings sent to the browser for this component.
 * The [client] TOML sub-table is promoted one level — access as t.rank, not t.client.rank.
 */

export interface HeaderClientT {
	_test_hello: string;
	_test_lang: string;
}
