// src/server/types/componentTranslations.ts

/**
 * This file is auto-generated by scripts/generate-translation-types.ts.
 * Do NOT edit manually!
 *
 * Provides strongly-typed shapes for every translation component loaded by
 * the server.  The [client] sub-table is intentionally excluded — those keys
 * are never accessed server-side.
 *
 * SharedT describes what the translation middleware injects into res.locals.t
 * (and therefore into every Nunjucks render context) on every request.
 */

export interface HeaderTranslations {
	nav: {
		learn: string;
		tools: string;
		leaderboard: string;
		news: string;
		donate: string;
		'learn-dropdown': {
			tutorial: string;
			checkmate_practice: string;
		};
		'tools-dropdown': {
			analysis_board: string;
			board_editor: string;
		};
	};
	actions: {
		login: string;
		register: string;
		profile: string;
		logout: string;
	};
	settings: {
		language: string;
		appearance: string;
		gameplay: string;
		perspective: string;
		sound: string;
		'appearance-dropdown': {
			theme: string;
			theme_light: string;
			theme_dark: string;
			legal_moves: string;
			legal_moves_squares: string;
			legal_moves_dots: string;
			coordinates: string;
			starfield: string;
			advanced_effects: string;
			board_tiles: string;
		};
		'gameplay-dropdown': {
			drag: string;
			premove: string;
			animations: string;
			fast_transitions: string;
			lingering_annotations: string;
		};
		'perspective-dropdown': {
			mouse_sensitivity: string;
			field_of_view: string;
			reset: string;
		};
		'sound-dropdown': {
			master_volume: string;
			ambience: string;
		};
	};
	ping: {
		label: string;
		unit: string;
	};
}

/**
 * The shape of `res.locals.t` injected by the translation middleware.
 * Every Nunjucks template receives these keys automatically.
 * Route handlers extend this with a `page` key for view-specific strings.
 */
export interface SharedT {
	header: HeaderTranslations;
}

/**
 * Extends SharedT with a view-specific `page` key.
 * Use as the type for `t` in page render contexts:
 * `res.render('index.njk', { t: { ...res.locals.t, page: ... } } satisfies PageContext<IndexTranslations>)`
 */
export type PageContext<P> = SharedT & { page: P };
