// src/server/types/response-translations.ts

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

/**
 * Flat dot-notation union type for getResponseTranslation().
 * Keys are derived from translation/responses/en-US.toml.
 */
export type ResponseTranslationKeys = 'placeholder';
