// scripts/insuffmat/writetable.ts

/**
 * Writes the site's src/shared/chess/logic/insuffmat/matingsets.ts from the generator's output:
 * every smallest mating set of both tables, keyed by the site's own
 * insufficientmaterial.getCanonicalKey, so the table and its lookup can never disagree. Each
 * table's cap is the highest level generated.
 *
 * Usage: npx tsx scripts/insuffmat/writetable.ts <out dir of generate.ts>
 */

import fs from 'node:fs';

import insufficientmaterial from '../../src/shared/chess/logic/insuffmat/insufficientmaterial.js';

import matesearch from './matesearch.js';

// Constants -------------------------------------------------------------------

const TABLE_FILE = 'src/shared/chess/logic/insuffmat/matingsets.ts';

// Table -----------------------------------------------------------------------

/** One table's smallest mating sets as sorted canonical keys, and its cap. */
function readTable(dir: string): { keys: string[]; cap: number } {
	const files = fs.readdirSync(dir).filter((file) => /^mates-\d+\.tsv$/.test(file));
	const cap = Math.max(...files.map((file) => Number(file.match(/\d+/)![0])));
	const keys = new Set<string>();
	for (const file of files)
		for (const line of fs.readFileSync(`${dir}/${file}`, 'utf8').split('\n').filter(Boolean)) {
			const [white, black] = matesearch.parse(line.split('\t')[0]!.split(' @')[0]!);
			const material = new Map<string, number>();
			for (const [kind, count] of Object.entries(white)) material.set(kind, count);
			for (const [kind, count] of Object.entries(black))
				material.set(kind.toLowerCase(), count);
			keys.add(insufficientmaterial.getCanonicalKey(material));
		}
	return { keys: [...keys].sort(), cap };
}

// Entry -----------------------------------------------------------------------

const outDir = process.argv[2];
if (outDir === undefined)
	throw Error('Usage: npx tsx scripts/insuffmat/writetable.ts <out dir of generate.ts>');
const unbounded = readTable(`${outDir}/unbounded`);
const bounded = readTable(`${outDir}/bounded`);
fs.writeFileSync(
	TABLE_FILE,
	`// ${TABLE_FILE}

/**
 * GENERATED by scripts/insuffmat/writetable.ts, do not edit. Every smallest piece set that can be
 * arranged into a checkmate, per board kind, up to each cap: white's pieces, then black's, as ICN
 * codes, bishops suffixed by square color. Terms, evidence and known holes: scripts/insuffmat/README.md.
 */

export default {
	cap: { unbounded: ${unbounded.cap}, bounded: ${bounded.cap} },
	unbounded:
		'${unbounded.keys.join(' ')}',
	bounded:
		'${bounded.keys.join(' ')}',
};
`,
);
console.log(
	`wrote ${unbounded.keys.length} unbounded (cap ${unbounded.cap}) and ${bounded.keys.length} bounded (cap ${bounded.cap}) mating sets`,
);
