// src/client/scripts/esm/views/icnvalidator/movegencheck.ts

/**
 * Compares the site's legal moves with the engine's at every position of a game.
 * Every move the engine generates must be legal on the site, and every move the site
 * lists individually must be generated by the engine. Slide squares are only checked
 * the first way, since the engine generates a sample of a slide, never all of it.
 */

import type { Player } from '../../../../../shared/chess/util/typeutil.js';
import type { GameFile } from '../../../../../shared/chess/logic/gamefile.js';
import type { CoordsKey } from '../../../../../shared/util/coordutil.js';
import type { LegalMoves } from '../../../../../shared/chess/logic/legalmoves.js';
import type { EngineWasmModule, WasmEngine } from '../../chess/enginewasm.js';

import coordutil from '../../../../../shared/util/coordutil.js';
import boardutil from '../../../../../shared/chess/logic/boardutil.js';
import movepiece from '../../../../../shared/chess/logic/movepiece.js';
import legalmoves from '../../../../../shared/chess/logic/legalmoves.js';

import engineicn from '../../chess/engineicn.js';
import gamecompressor from '../../chess/gamecompressor.js';

// Types -----------------------------------------------------------------------

/** The engine glue's exports the check uses. */
export interface MovegenWasmModule extends EngineWasmModule {
	Engine: {
		/** Constructs an engine at the position described by `icn`. */
		from_icn: (icn: string, config: Record<string, never>) => WasmEngine;
	};
}

// Game Replay -----------------------------------------------------------------

/**
 * Throws if the site and the engine disagree on the legal moves at any position
 * of the game, naming the first disagreement and how many there were in total.
 * Leaves the game at its final position.
 */
function validate(gamefile: GameFile, wasm: MovegenWasmModule): void {
	movepiece.goToMove(gamefile, -1, (move) => movepiece.applyMove(gamefile, move, false, true));

	let first: string | undefined;
	let count = 0;
	for (let ply = 0; ; ply++) {
		const mismatches = comparePosition(gamefile, wasm);
		if (mismatches.length > 0) {
			first ??= `ply ${ply}, ${mismatches[0]}`;
			count += mismatches.length;
		}
		const move = gamefile.moves[ply];
		if (move === undefined) break;
		movepiece.applyMove(gamefile, move, true, true);
	}

	if (first !== undefined) throw new Error(`${count} mismatch(es). First at ${first}`);
}

// Position Comparison ---------------------------------------------------------

/** Every disagreement between the site's and the engine's legal moves at the viewed position. */
function comparePosition(gamefile: GameFile, wasm: MovegenWasmModule): string[] {
	const color = gamefile.whosTurn;
	const siteMoves = getSiteMoves(gamefile, color);
	const engineMoves = getEngineMoves(gamefile, wasm);
	return [
		...findEngineOnlyMoves(gamefile, color, siteMoves, engineMoves),
		...findSiteOnlyMoves(siteMoves, engineMoves),
	];
}

/** The site's legal moves for every piece of `color`, keyed by the piece's square. */
function getSiteMoves(gamefile: GameFile, color: Player): Map<CoordsKey, LegalMoves> {
	const siteMoves = new Map<CoordsKey, LegalMoves>();
	for (const piece of boardutil.iteratePiecesOfColor(gamefile.pieces, color)) {
		siteMoves.set(
			coordutil.getKeyFromCoords(piece.coords),
			legalmoves.calculateAll(gamefile, piece),
		);
	}
	return siteMoves;
}

/** The engine's legal moves at the viewed position, as "x,y>x,y" tokens without promotions. */
function getEngineMoves(gamefile: GameFile, wasm: MovegenWasmModule): Set<string> {
	const longform = gamecompressor.compressGamefile(gamefile, true);
	engineicn.prepareForEngine(longform);
	const engine = wasm.Engine.from_icn(engineicn.serialize(longform), {});
	try {
		return new Set(engine.get_legal_moves_js().map((move) => `${move.from}>${move.to}`));
	} finally {
		engine.free();
	}
}

/** The engine's moves the site does not allow. */
function findEngineOnlyMoves(
	gamefile: GameFile,
	color: Player,
	siteMoves: Map<CoordsKey, LegalMoves>,
	engineMoves: Set<string>,
): string[] {
	const mismatches: string[] = [];
	for (const token of engineMoves) {
		const [from, to] = token.split('>') as [CoordsKey, CoordsKey];
		const legal = siteMoves.get(from);
		const startCoords = coordutil.getCoordsFromKey(from);
		const endCoords = coordutil.getCoordsFromKey(to);
		if (legal && legalmoves.checkIfMoveLegal(gamefile, legal, startCoords, endCoords, color))
			continue;
		mismatches.push(`the engine generates ${token}, which the site rejects`);
	}
	return mismatches;
}

/** The site's individual moves the engine does not generate. */
function findSiteOnlyMoves(
	siteMoves: Map<CoordsKey, LegalMoves>,
	engineMoves: Set<string>,
): string[] {
	const mismatches: string[] = [];
	for (const [from, legal] of siteMoves) {
		for (const coords of legal.individual) {
			const token = `${from}>${coordutil.getKeyFromCoords(coords)}`;
			if (!engineMoves.has(token))
				mismatches.push(`the site allows ${token}, which the engine does not generate`);
		}
	}
	return mismatches;
}

// Exports ---------------------------------------------------------------------

export default {
	// Game Replay
	validate,
};
