// src/client/types/client-translations.d.ts

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

interface ClientTranslations {}

/**
 * Client-side translations. The only component actually available
 * will be what is included on the page the script is running on.
 */
declare const t: ClientTranslations;
