// scripts/generate-translation-types.ts

/**
 * Generates TypeScript types from the component translation TOML files.
 *
 * For each translation/  <component>/en-US.toml it produces:
 *   - A server-side interface (full object, excluding the [client] sub-table)
 *   - A client-side interface from the [client] sub-table only (keys promoted one level up)
 *
 * Outputs:
 *   src/server/types/componentTranslations.ts  — server-only interfaces + SharedT
 *   src/client/types/translations/<component>.ts — client-only interface per component
 *                                                  (only written when [client] exists)
 */

import fs from 'fs';
import path from 'path';
import { parse } from 'smol-toml';
import { fileURLToPath } from 'node:url';

type TomlValue = string | number | boolean | TomlValue[] | TomlObject;
type TomlObject = { [key: string]: TomlValue };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const translationRoot = path.join(__dirname, '../translation');
const serverTypesOut = path.join(__dirname, '../src/server/types/componentTranslations.ts');
const clientTypesDir = path.join(__dirname, '../src/client/types/translations');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isObject(v: TomlValue | undefined): v is TomlObject {
	return v !== null && v !== undefined && typeof v === 'object' && !Array.isArray(v);
}

/**
 * Renders a TypeScript interface body from a TOML object.
 * Arrays become `string[]`, nested objects recurse, primitives become `string`.
 */
function renderInterfaceBody(obj: TomlObject, indent = 1): string {
	const pad = '\t'.repeat(indent);
	const lines: string[] = [];
	for (const [key, value] of Object.entries(obj)) {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
		if (isObject(value)) {
			lines.push(`${pad}${safeKey}: {`);
			lines.push(renderInterfaceBody(value, indent + 1));
			lines.push(`${pad}};`);
		} else if (Array.isArray(value)) {
			lines.push(`${pad}${safeKey}: string[];`);
		} else {
			lines.push(`${pad}${safeKey}: string;`);
		}
	}
	return lines.join('\n');
}

/** Capitalises the first letter of a string. */
function capitalise(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Converts a kebab/snake component name to a PascalCase type name suffix.
 * E.g. "header" → "Header", "create-account" → "CreateAccount"
 */
function toPascal(name: string): string {
	return name.split(/[-_]/).map(capitalise).join('');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function generateTypes(): void {
	// Collect all component subdirectories that have an en-US.toml
	const componentDirs = fs
		.readdirSync(translationRoot, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.map((d) => d.name)
		.filter((name) => fs.existsSync(path.join(translationRoot, name, 'en-US.toml')));

	if (componentDirs.length === 0) {
		console.warn('[generate-translation-types] No component TOML files found — nothing to do.');
		return;
	}

	// ---- server types -------------------------------------------------------
	let serverOutput = `// src/server/types/componentTranslations.ts

/**
 * This file is auto-generated by scripts/generate-translation-types.ts.
 * Do NOT edit manually!
 *
 * Provides strongly-typed shapes for every translation component loaded by
 * the server.  The [client] sub-table is intentionally excluded — those keys
 * are never accessed server-side.
 *
 * SharedT describes what the translation middleware injects into res.locals.t
 * (and therefore into every Nunjucks render context) on every request.
 */

`;

	// Track which components exist for SharedT
	const sharedComponents: string[] = [];

	for (const componentName of componentDirs) {
		const tomlPath = path.join(translationRoot, componentName, 'en-US.toml');
		const parsed = parse(fs.readFileSync(tomlPath, 'utf-8')) as TomlObject;

		// Remove [client] from the server-side view
		const serverObj: TomlObject = {};
		for (const [k, v] of Object.entries(parsed)) {
			if (k !== 'client') serverObj[k] = v;
		}

		const typeName = `${toPascal(componentName)}Translations`;
		sharedComponents.push(componentName);

		serverOutput += `export interface ${typeName} {\n${renderInterfaceBody(serverObj)}\n}\n\n`;

		// ---- client types (only when [client] sub-table exists) -------------
		const clientObj = parsed['client'];
		if (isObject(clientObj)) {
			const typedClientObj = clientObj as TomlObject;
			const clientTypeName = `${toPascal(componentName)}ClientT`;
			const clientRelPath = `src/client/types/translations/${componentName}.ts`;
			const clientOutput = `// ${clientRelPath}

/**
 * This file is auto-generated by scripts/generate-translation-types.ts.
 * Do NOT edit manually!
 *
 * Client-side translation keys for the "${componentName}" component.
 * These are the only translation strings sent to the browser for this component.
 * The [client] TOML sub-table is promoted one level — access as t.rank, not t.client.rank.
 */

export interface ${clientTypeName} {
${renderInterfaceBody(typedClientObj)}
}
`;
			fs.mkdirSync(clientTypesDir, { recursive: true });
			const clientOutPath = path.join(clientTypesDir, `${componentName}.ts`);
			fs.writeFileSync(clientOutPath, clientOutput, 'utf-8');
			console.log(`[generate-translation-types] Wrote ${clientRelPath}`);
		}
	}

	// SharedT — the type of res.locals.t (what every Nunjucks template always sees)
	// "Shared" components are header and footer (always present). Others are added per-route.
	const alwaysPresentComponents = sharedComponents.filter((c) =>
		['header', 'footer', 'common'].includes(c),
	);
	const sharedMembers = alwaysPresentComponents
		.map((c) => `\t${c}: ${toPascal(c)}Translations;`)
		.join('\n');

	serverOutput += `/**
 * The shape of \`res.locals.t\` injected by the translation middleware.
 * Every Nunjucks template receives these keys automatically.
 * Route handlers extend this with a \`page\` key for view-specific strings.
 */
export interface SharedT {
${sharedMembers}
}

/**
 * Extends SharedT with a view-specific \`page\` key.
 * Use as the type for \`t\` in page render contexts:
 * \`res.render('index.njk', { t: { ...res.locals.t, page: ... } } satisfies PageContext<IndexTranslations>)\`
 */
export type PageContext<P> = SharedT & { page: P };
`;

	fs.mkdirSync(path.dirname(serverTypesOut), { recursive: true });
	fs.writeFileSync(serverTypesOut, serverOutput, 'utf-8');
	console.log(
		`[generate-translation-types] Wrote src/server/types/componentTranslations.ts (${componentDirs.length} components).`,
	);
}

try {
	generateTypes();
} catch (error) {
	console.error('Error generating translation types:', error);
	process.exit(1);
}
