// scripts/generate-component-translation-types.ts

/**
 * Generates the ScriptTranslations interface
 * (one property per component that has a [script] sub-table).
 *
 * Output: src/shared/types/script-translations.d.ts
 * Lives in shared/ so the server can type getScriptTranslations() against the same
 * shape the client consumes via the global `t`.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { parse, TomlTable } from 'smol-toml';

import tconfig from '../src/server/config/translationconfig';
import { getComponentNames } from '../src/server/config/componentTranslationLoader';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Constants -----------------------------------------------------------------

const SCRIPT_OUTPUT_FILE = path.join(__dirname, '../src/shared/types/script-translations.d.ts');

// Functions -----------------------------------------------------------------------

/** Generates the ScriptTranslations declaration file for components with [script] sections. */
function generateScriptTranslations(): void {
	const componentDirs = getComponentNames();

	const properties: string[] = [];

	for (const componentName of componentDirs) {
		const englishTomlPath = path.join(
			tconfig.TRANSLATION_FOLDER,
			componentName,
			`${tconfig.DEFAULT_LANGUAGE}.toml`,
		);
		if (!fs.existsSync(englishTomlPath))
			throw new Error(`Component "${componentName}" is missing the English source.`);

		const parsed = parse(fs.readFileSync(englishTomlPath, 'utf-8'));
		const scriptTable = extractScriptTable(parsed, componentName);
		if (!scriptTable) continue; // This component doesn't have script translations, skip.

		const body = generateNestedType(scriptTable, 2);
		properties.push(`\t${componentName}: {\n${body}\n\t};`);
	}

	const output = `// ${path.relative(path.join(__dirname, '..'), SCRIPT_OUTPUT_FILE)}

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

/**
 * Shape of all script-facing translation tables, keyed by component name.
 * Client scripts access these via the global \`t\` declared in
 * src/client/types/globals.d.ts; the server reads them through the typed
 * \`getScriptTranslations(component, lang)\` helper.
 */
export interface ScriptTranslations {
${properties.join('\n')}
}
`;

	fs.mkdirSync(path.dirname(SCRIPT_OUTPUT_FILE), { recursive: true });
	fs.writeFileSync(SCRIPT_OUTPUT_FILE, output, 'utf-8');

	console.log(
		`[generate-component-translation-types] Generated ScriptTranslations with ${properties.length} component(s).`,
	);
}

/**
 * Returns the script-facing subtree of a parsed component TOML, or `undefined`
 * if the component ships no script translations. Mirrors the loader's split:
 * `script_only = true` promotes the whole file (minus the flag); otherwise the
 * `[script]` subtable is the script half.
 */
function extractScriptTable(parsed: TomlTable, componentName: string): TomlTable | undefined {
	if (parsed['script_only'] === true) {
		const { script_only: _flag, ...rest } = parsed;
		return rest;
	}
	const scriptTable = parsed['script'];
	if (!scriptTable) return undefined;
	if (typeof scriptTable !== 'object' || Array.isArray(scriptTable))
		throw new Error(`Component "${componentName}" [script] table should be an object.`);
	return scriptTable as TomlTable;
}

/** Generates a TypeScript type body from a nested object structure. */
function generateNestedType(obj: TomlTable | any, indentLevel = 1): string {
	const indent = '\t'.repeat(indentLevel);
	const lines: string[] = [];

	for (const [key, value] of Object.entries(obj)) {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;

		if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: {`);
			lines.push(generateNestedType(value, indentLevel + 1));
			lines.push(`${indent}};`);
		} else if (Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: string[];`);
		} else {
			lines.push(`${indent}${safeKey}: string;`);
		}
	}

	return lines.join('\n');
}

try {
	generateScriptTranslations();
} catch (error) {
	console.error('Error generating component translation types:', error);
	process.exit(1);
}
