// scripts/generate-component-translation-types.ts

/**
 * Generates TypeScript type files for component translations:
 *
 * 1. Client translations: A ClientTranslations interface (one property per component
 *    that has a [client] sub-table).
 *    Output: src/shared/types/client-translations.d.ts
 *    Lives in shared/ so the server can type getClientTranslation() against the same
 *    shape the client consumes via the global `t`.
 *
 * 2. Response translations: A ResponseTranslationKeys flat dot-notation union type
 *    derived from the "responses" component.
 *    Output: src/server/types/response-translations.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { parse, TomlTable } from 'smol-toml';

import tconfig from '../src/server/config/translationconfig';
import { getComponentNames } from '../src/server/config/componentTranslationLoader';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Constants -----------------------------------------------------------------

const CLIENT_OUTPUT_FILE = path.join(__dirname, '../src/shared/types/client-translations.d.ts');
const RESPONSE_OUTPUT_FILE = path.join(__dirname, '../src/server/types/response-translations.ts');

// Functions -----------------------------------------------------------------------

/** Main function to generate all component translation type files. */
function generateTypes(): void {
	generateClientTranslations();
	generateResponseTranslations();
}

/** Generates the ClientTranslations declaration file for components with [client] sections. */
function generateClientTranslations(): void {
	const componentDirs = getComponentNames();

	const properties: string[] = [];

	for (const componentName of componentDirs) {
		if (componentName === tconfig.RESPONSES_COMPONENT) continue; // Contains no client translations, skip.

		const englishTomlPath = path.join(
			tconfig.TRANSLATION_FOLDER,
			componentName,
			`${tconfig.DEFAULT_LANGUAGE}.toml`,
		);
		if (!fs.existsSync(englishTomlPath))
			throw new Error(`Component "${componentName}" is missing the English source.`);

		const parsed = parse(fs.readFileSync(englishTomlPath, 'utf-8'));
		const clientTable = parsed['client'];
		if (!clientTable) continue; // This component doesn't have client translations, skip.
		if (typeof clientTable !== 'object' || Array.isArray(clientTable))
			throw new Error(`Component "${componentName}" [client] table should be an object.`);

		const body = generateNestedType(clientTable, 2);
		properties.push(`\t${componentName}: {\n${body}\n\t};`);
	}

	const output = `// ${path.relative(path.join(__dirname, '..'), CLIENT_OUTPUT_FILE)}

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

/**
 * Shape of all client-shipped translation tables, keyed by component name.
 * Client scripts access these via the global \`t\` declared in
 * src/client/types/globals.d.ts; the server reads them through the typed
 * \`getClientTranslation(component, lang)\` helper.
 */
export interface ClientTranslations {
${properties.join('\n')}
}
`;

	fs.mkdirSync(path.dirname(CLIENT_OUTPUT_FILE), { recursive: true });
	fs.writeFileSync(CLIENT_OUTPUT_FILE, output, 'utf-8');

	console.log(
		`[generate-component-translation-types] Generated ClientTranslations with ${properties.length} component(s).`,
	);
}

/** Generates the ResponseTranslationKeys type file from the "responses" component TOML. */
function generateResponseTranslations(): void {
	const englishTomlPath = path.join(
		tconfig.TRANSLATION_FOLDER,
		tconfig.RESPONSES_COMPONENT,
		`${tconfig.DEFAULT_LANGUAGE}.toml`,
	);
	if (!fs.existsSync(englishTomlPath))
		throw new Error(
			`Component "${tconfig.RESPONSES_COMPONENT}" is missing the English source TOML.`,
		);

	const parsed = parse(fs.readFileSync(englishTomlPath, 'utf-8'));
	const dotPaths = generateDotPaths(parsed);

	const output = `// ${path.relative(path.join(__dirname, '..'), RESPONSE_OUTPUT_FILE)}

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

/**
 * Flat dot-notation union type for getResponseTranslation().
 * Keys are derived from translation/responses/en-US.toml.
 */
export type ResponseTranslationKeys =${dotPaths.map((p) => `\n\t| '${p}'`).join('')};
`;

	fs.mkdirSync(path.dirname(RESPONSE_OUTPUT_FILE), { recursive: true });
	fs.writeFileSync(RESPONSE_OUTPUT_FILE, output, 'utf-8');

	console.log(
		`[generate-component-translation-types] Generated ResponseTranslationKeys with ${dotPaths.length} key(s).`,
	);
}

/** Generates a TypeScript type body from a nested object structure. */
function generateNestedType(obj: TomlTable | any, indentLevel = 1): string {
	const indent = '\t'.repeat(indentLevel);
	const lines: string[] = [];

	for (const [key, value] of Object.entries(obj)) {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;

		if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: {`);
			lines.push(generateNestedType(value, indentLevel + 1));
			lines.push(`${indent}};`);
		} else if (Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: string[];`);
		} else {
			lines.push(`${indent}${safeKey}: string;`);
		}
	}

	return lines.join('\n');
}

/**
 * Recursively generates all dot-notation paths for a nested TOML object.
 * @param obj - The object to traverse
 * @param prefix - The current path prefix
 * @returns Array of dot-notation paths
 */
function generateDotPaths(obj: TomlTable | any, prefix = ''): string[] {
	const paths: string[] = [];
	for (const [key, value] of Object.entries(obj)) {
		const path = prefix ? `${prefix}.${key}` : key;
		if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
			// Recursively traverse nested objects
			paths.push(...generateDotPaths(value, path));
		} else {
			// Leaf node - add the path
			paths.push(path);
		}
	}

	return paths;
}

try {
	generateTypes();
} catch (error) {
	console.error('Error generating component translation types:', error);
	process.exit(1);
}
