// scripts/generate-client-translation-types.ts

/**
 * Generates a single ambient TypeScript declaration file containing
 * the ClientTranslations interface (one property per component that
 * has a [client] sub-table).
 *
 * Output: src/client/types/client-translations.d.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { parse, TomlTable } from 'smol-toml';

import tconfig from '../src/server/config/translationconfig';
import { getComponentNames } from '../src/server/config/componentTranslationLoader';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Constants -----------------------------------------------------------------

const OUTPUT_FILE = path.join(__dirname, '../src/client/types/client-translations.d.ts');

// Functions -----------------------------------------------------------------------

/** Main function to generate the ClientTranslations declaration file. */
function generateTypes(): void {
	const componentDirs = getComponentNames();

	const properties: string[] = [];

	for (const componentName of componentDirs) {
		const englishTomlPath = path.join(
			tconfig.TRANSLATION_FOLDER,
			componentName,
			`${tconfig.DEFAULT_LANGUAGE}.toml`,
		);
		if (!fs.existsSync(englishTomlPath))
			throw new Error(`Component "${componentName}" is missing the English source.`);

		const parsed = parse(fs.readFileSync(englishTomlPath, 'utf-8'));
		const clientTable = parsed['client'];
		if (!clientTable) continue; // This component doesn't have client translations, skip.
		if (typeof clientTable !== 'object' || Array.isArray(clientTable))
			throw new Error(`Component "${componentName}" [client] table should be an object.`);

		const body = generateNestedType(clientTable, 2);
		properties.push(`\t${componentName}: {\n${body}\n\t};`);
	}

	const output = `// ${path.relative(path.join(__dirname, '..'), OUTPUT_FILE)}

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

interface ClientTranslations {
${properties.join('\n')}
}

/**
 * Client-side translations. The only component actually available
 * will be what is included on the page the script is running on.
 */
declare const t: ClientTranslations;
`;

	fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
	fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

	console.log(
		`[generate-component-translation-types] Generated ClientTranslations with ${properties.length} component(s).`,
	);
}

/** Generates a TypeScript type body from a nested object structure. */
function generateNestedType(obj: TomlTable | any, indentLevel = 1): string {
	const indent = '\t'.repeat(indentLevel);
	const lines: string[] = [];

	for (const [key, value] of Object.entries(obj)) {
		const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;

		if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: {`);
			lines.push(generateNestedType(value, indentLevel + 1));
			lines.push(`${indent}};`);
		} else if (Array.isArray(value)) {
			lines.push(`${indent}${safeKey}: string[];`);
		} else {
			lines.push(`${indent}${safeKey}: string;`);
		}
	}

	return lines.join('\n');
}

try {
	generateTypes();
} catch (error) {
	console.error('Error generating component translation types:', error);
	process.exit(1);
}
