// src/shared/types/script-translations.d.ts

/**
 * Auto-generated by scripts/generate-component-translation-types.ts on build.
 * Do NOT edit manually!
 */

/**
 * Shape of all script-facing translation tables, keyed by component name.
 * Client scripts access these via the global `t` declared in
 * src/client/types/globals.d.ts; the server reads them through the typed
 * `getScriptTranslations(component, lang)` helper.
 */
export interface ScriptTranslations {
	header: {
		settings: {
			appearance_dropdown: {
				theme_light: string;
				theme_dark: string;
				legal_moves_squares: string;
				legal_moves_dots: string;
			};
		};
	};
	index: {
		lobby_buttons: {
			create_online: string;
			challenge_friend: string;
			play_computer: string;
		};
		lobby: {
			cancel_seek: string;
			accept_seek: string;
		};
		modal: {
			variant_selector: {
				saved_positions: string;
				local_load_failed: string;
				cloud_load_failed: string;
			};
		};
	};
	login: {
		network_error: string;
	};
	responses: {
		seeks: {
			already_in_game: string;
			rated_requires_verified: string;
			game_aborted: string;
			cloud_requires_sign_in: string;
			cloud_not_found: string;
		};
		auth: {
			invalid_credentials: string;
			login_failed: string;
			login_retry_in_one: string;
			login_retry_in_other: string;
		};
		rate_limiting: {
			generic: string;
			account_creations: string;
			verify_emails: string;
		};
		editor_saves: {
			must_be_signed_in: string;
			position_not_found: string;
			limit_reached: string;
			server_error: string;
		};
	};
	shared: {
		error_fallback: string;
		user_status: {
			guest_indicator: string;
			you_indicator: string;
		};
		variants: {
			Classical: string;
			Core: string;
			Standarch: string;
			Space_Classic: string;
			CoaIP: string;
			Space: string;
			Obstocean: string;
			Chess: string;
			Confined_Classical: string;
			Classical_Plus: string;
			Pawndard: string;
			Knightline: string;
			Palace: string;
			CoaIP_HO: string;
			CoaIP_RO: string;
			CoaIP_NO: string;
			Knighted_Chess: string;
			Abundance: string;
			Amazon_Chandelier: string;
			Containment: string;
			Pawn_Horde: string;
			'4x4x4x4_Chess': string;
			'5D_Chess': string;
			Omega: string;
			Omega_Squared: string;
			Omega_Cubed: string;
			Omega_Fourth: string;
		};
		variant_groups: {
			standard: {
				name: string;
				description: string;
			};
			horde: {
				name: string;
				description: string;
			};
			'4D': {
				name: string;
				description: string;
			};
			showcase: {
				name: string;
				description: string;
			};
			custom: {
				name: string;
				description: string;
				display_label: string;
			};
		};
		speeds: {
			bullet: string;
			blitz: string;
			rapid: string;
			classical: string;
			infinite: string;
		};
		game_modes: {
			casual: string;
			rated: string;
		};
		sides: {
			random: string;
			white: string;
			black: string;
			red: string;
			blue: string;
			yellow: string;
			green: string;
			neutral: string;
		};
		modifiers: {
			'slide-limit': {
				name: string;
				description: string;
			};
		};
		position_errors: {
			invalid_icn: string;
			icn_missing_position: string;
			mixed_player_modes: string;
			incomplete_turn_order: string;
			position_too_large: string;
			gargoyles_not_allowed: string;
			invalid_player_id: string;
			player_missing_pieces: string;
			player_missing_royal: string;
			consecutive_turns_with_checkmate: string;
			too_many_royals_for_checkmate: string;
			king_capture_on_turn_1: string;
		};
		variant_preview: {
			four_d_movement: string;
			black_moves_first: string;
			turn_order: string;
			win_by: string;
			color_wins_by: string;
			no_promotion: string;
			promotion_prefix: string;
			no_move_rule: string;
			move_rule: string;
			en_passant: string;
			plies_since_capture: string;
			slide_limit_rule: string;
			win_conditions: {
				checkmate: string;
				royalcapture: string;
				allroyalscaptured: string;
				allpiecescaptured: string;
				koth: string;
			};
		};
	};
}
